apiVersion: v1
kind: ConfigMap
metadata:
  name: webflux-kafka-backend-config
  namespace: webflux-kafka-poc
data:
  ITEM_DATASOURCE_DRIVER: "com.mysql.cj.jdbc.Driver"
  ITEM_MSSQL_URL: "jdbc:mysql://your-rds-endpoint:3306/item_poc_source?useSSL=false&allowPublicKeyRetrieval=true"
  ITEM_MYSQL_URL: "jdbc:mysql://your-rds-endpoint:3306/item_poc?useSSL=false&allowPublicKeyRetrieval=true"
  ITEM_KAFKA_BOOTSTRAP_SERVERS: "your-msk-bootstrap:9092"
  ITEM_KAFKA_TOPIC: "Item_Topic"
  ITEM_CORS_ALLOWED_ORIGINS: "https://your-ui-domain"
  ITEM_GATEWAY_URL: "http://localhost:8081/item-kafka/app/send-items/v1"


