apiVersion: apps/v1
kind: Deployment
metadata:
  name: item-kafka-backend
  namespace: item-kafka-poc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: item-kafka-backend
  template:
    metadata:
      labels:
        app: item-kafka-backend
    spec:
      containers:
        - name: item-kafka-backend
          image: 123456789012.dkr.ecr.af-south-1.amazonaws.com/item-kafka-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          envFrom:
            - configMapRef:
                name: item-kafka-backend-config
            - secretRef:
                name: item-kafka-backend-secret
          readinessProbe:
            httpGet:
              path: /agent/swagger-ui.html
              port: 8082
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /agent/swagger-ui.html
              port: 8082
            initialDelaySeconds: 60
            periodSeconds: 20
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1024Mi"

